<?php

require_once 'TranslateApi.php';

generate();

/**
 * The data source is obtained through the data interface generated by the cloud function from Tencent, and then the cache file is generated for retrieving the data
 */
function generate()
{
    // Generate the cache file interface
    $q_list_url = "http://service-mdhh5nvy-1304485299.gz.apigw.tencentcs.com/release/list";

    $q_list =  json_decode(file_get_contents($q_list_url), true);

    $tmx = './web/TMX';

    if(!is_dir($tmx)){
        mkdir($tmx);
    }

    $dir_list = json_decode(file_get_contents('./app/config/sources/tools.json'),true);

    // Loop languages
    foreach ($dir_list as $k => $item){

        // Loop to create the language directory
        if(!is_dir($tmx.'/'.$item)){
            mkdir($tmx.'/'.$item);
        }

        // Loop domains
        foreach ($q_list as $k1 => $item1){
            // Loop the key value and sentences in each domain
            $res = [];
            foreach ($item1 as $url => $keywords){
                $res[$url]  = TranslateApi::run($keywords, $item);
            }

            file_put_contents($tmx.'/'.$item.'/cache_'.$item.'_'.$k1.'.json', json_encode($res,JSON_UNESCAPED_UNICODE));

            $text = '<?php $tmx='.var_export($res,true).';';

            file_put_contents($tmx.'/'.$item.'/cache_'.$item.'_'.$k1.'.php', $text);

        }


    }


}

